# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a88fc782c78a9a13d0e023403dfa7ac1c4215ff59fbbea75820e94608fc3e03983054feb596ad03162a4afb70a8c47a384811ae1bc0f2081967c5e503b3efd6

test:
  secret_key_base: 09af7efb55cc9895e9f3746d98cf3a911aa51c949e29883dc5825825f57c74c5206e5b66148582b13b66cbd846dceb4afd48bd277cc87d1afb4f00b934419f42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
